// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9t54ATWRdYNH11Fsi_az9Uz91r1Dlzao',
    appId: '1:401032461458:web:38241cb8799f0001d97a4b',
    messagingSenderId: '401032461458',
    projectId: 'go-home-ease',
    authDomain: 'go-home-ease.firebaseapp.com',
    storageBucket: 'go-home-ease.firebasestorage.app',
    measurementId: 'G-7ERM1VTW2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFkvEWp0Mlq8YmL7NBF3d2ZdG0qwHjNpM',
    appId: '1:401032461458:android:26fbe518b23d2976d97a4b',
    messagingSenderId: '401032461458',
    projectId: 'go-home-ease',
    storageBucket: 'go-home-ease.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjzFivAkopQ08qZPnyxoSwIgT_zmqQd4k',
    appId: '1:401032461458:ios:4a6cdd1db8122941d97a4b',
    messagingSenderId: '401032461458',
    projectId: 'go-home-ease',
    storageBucket: 'go-home-ease.firebasestorage.app',
    iosBundleId: 'com.example.homease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjzFivAkopQ08qZPnyxoSwIgT_zmqQd4k',
    appId: '1:401032461458:ios:4a6cdd1db8122941d97a4b',
    messagingSenderId: '401032461458',
    projectId: 'go-home-ease',
    storageBucket: 'go-home-ease.firebasestorage.app',
    iosBundleId: 'com.example.homease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9t54ATWRdYNH11Fsi_az9Uz91r1Dlzao',
    appId: '1:401032461458:web:8d18e448d5737592d97a4b',
    messagingSenderId: '401032461458',
    projectId: 'go-home-ease',
    authDomain: 'go-home-ease.firebaseapp.com',
    storageBucket: 'go-home-ease.firebasestorage.app',
    measurementId: 'G-Q5RPQPQR78',
  );
}
